USE sql_store;

INSERT INTO orders (customer_id, order_date, status)
VALUES (1, '2019-01-02', 1);

INSERT INTO order_items
VALUES (LAST_INSERT_ID(), 1, 1, 2.95),
       (LAST_INSERT_ID(), 2, 1, 3.95)

/*
 orders table is parent; order_items in child
 LAST_INSERT_ID is a built-in function that returns the id generated by the inserted row
 In this case, the id can then be used to insert the appropriate rows into order_items
 using the order_id from orders
 */